// Tehillim - selected psalms
const psalmPrayers = {
    psalm_27: {
        title: "Psalm 27 (L'Dovid)",
        words: [
            { h: "לְדָוִד", at: "L'Dovid", newParagraph: true },
            { h: "יְיָ", at: "Adonai" },
            { h: "אוֹרִי", at: "ori" },
            { h: "וְיִשְׁעִי", at: "v'yishi" },
            { h: "מִמִּי", at: "mimi" },
            { h: "אִירָא", at: "iro" },
            { h: "יְיָ", at: "Adonai" },
            { h: "מָעוֹז", at: "ma'oz" },
            { h: "חַיַּי", at: "chayai" },
            { h: "מִמִּי", at: "mimi" },
            { h: "אֶפְחָד", at: "efchod" },

            { h: "בִּקְרֹב", at: "Bikrov", newParagraph: true },
            { h: "עָלַי", at: "alai" },
            { h: "מְרֵעִים", at: "m'rei'im" },
            { h: "לֶאֱכֹל", at: "le'echol" },
            { h: "אֶת", at: "es" },
            { h: "בְּשָׂרִי", at: "b'sori" },
            { h: "צָרַי", at: "tzorai" },
            { h: "וְאֹיְבַי", at: "v'oyvai" },
            { h: "לִי", at: "li" },
            { h: "הֵמָּה", at: "heimah" },
            { h: "כָשְׁלוּ", at: "koshlu" },
            { h: "וְנָפָלוּ", at: "v'nofolu" },

            { h: "אִם", at: "Im", newParagraph: true },
            { h: "תַּחֲנֶה", at: "tachaneh" },
            { h: "עָלַי", at: "alai" },
            { h: "מַחֲנֶה", at: "machaneh" },
            { h: "לֹא", at: "lo" },
            { h: "יִירָא", at: "yiro" },
            { h: "לִבִּי", at: "libi" },
            { h: "אִם", at: "im" },
            { h: "תָּקוּם", at: "tokum" },
            { h: "עָלַי", at: "alai" },
            { h: "מִלְחָמָה", at: "milchomoh" },
            { h: "בְּזֹאת", at: "b'zos" },
            { h: "אֲנִי", at: "ani" },
            { h: "בוֹטֵחַ", at: "votei'ach" },

            { h: "אַחַת", at: "Achas", newParagraph: true },
            { h: "שָׁאַלְתִּי", at: "sho'alti" },
            { h: "מֵאֵת", at: "mei'eis" },
            { h: "יְיָ", at: "Adonai" },
            { h: "אוֹתָהּ", at: "osoh" },
            { h: "אֲבַקֵּשׁ", at: "avakeish" },
            { h: "שִׁבְתִּי", at: "shivti" },
            { h: "בְּבֵית", at: "b'veis" },
            { h: "יְיָ", at: "Adonai" },
            { h: "כָּל", at: "kol" },
            { h: "יְמֵי", at: "y'mei" },
            { h: "חַיַּי", at: "chayai" },
            { h: "לַחֲזוֹת", at: "lachazos" },
            { h: "בְּנֹעַם", at: "b'no'am" },
            { h: "יְיָ", at: "Adonai" },
            { h: "וּלְבַקֵּר", at: "u'lvakeir" },
            { h: "בְּהֵיכָלוֹ", at: "b'heicholo" },

            { h: "כִּי", at: "Ki", newParagraph: true },
            { h: "יִצְפְּנֵנִי", at: "yitzp'neini" },
            { h: "בְּסֻכֹּה", at: "b'suko" },
            { h: "בְּיוֹם", at: "b'yom" },
            { h: "רָעָה", at: "ro'oh" },
            { h: "יַסְתִּרֵנִי", at: "yastireini" },
            { h: "בְּסֵתֶר", at: "b'seiser" },
            { h: "אָהֳלוֹ", at: "ohalo" },
            { h: "בְּצוּר", at: "b'tzur" },
            { h: "יְרוֹמְמֵנִי", at: "y'rom'meini" },

            { h: "וְעַתָּה", at: "V'atah", newParagraph: true },
            { h: "יָרוּם", at: "yarum" },
            { h: "רֹאשִׁי", at: "roshi" },
            { h: "עַל", at: "al" },
            { h: "אֹיְבַי", at: "oyvai" },
            { h: "סְבִיבוֹתַי", at: "s'vivosai" },
            { h: "וְאֶזְבְּחָה", at: "v'ezb'choh" },
            { h: "בְאָהֳלוֹ", at: "v'ohalo" },
            { h: "זִבְחֵי", at: "zivchei" },
            { h: "תְרוּעָה", at: "s'ru'oh" },
            { h: "אָשִׁירָה", at: "oshiroh" },
            { h: "וַאֲזַמְּרָה", at: "va'azam'roh" },
            { h: "לַייָ", at: "l'Adonai" },

            { h: "שְׁמַע", at: "Sh'ma", newParagraph: true },
            { h: "יְיָ", at: "Adonai" },
            { h: "קוֹלִי", at: "koli" },
            { h: "אֶקְרָא", at: "ekro" },
            { h: "וְחָנֵּנִי", at: "v'choneini" },
            { h: "וַעֲנֵנִי", at: "va'aneini" },

            { h: "לְךָ", at: "L'cho", newParagraph: true },
            { h: "אָמַר", at: "omar" },
            { h: "לִבִּי", at: "libi" },
            { h: "בַּקְּשׁוּ", at: "bakshu" },
            { h: "פָנָי", at: "fonai" },
            { h: "אֶת", at: "es" },
            { h: "פָּנֶיךָ", at: "ponecho" },
            { h: "יְיָ", at: "Adonai" },
            { h: "אֲבַקֵּשׁ", at: "avakeish" },

            { h: "אַל", at: "Al", newParagraph: true },
            { h: "תַּסְתֵּר", at: "tasteir" },
            { h: "פָּנֶיךָ", at: "ponecho" },
            { h: "מִמֶּנִּי", at: "mimeni" },
            { h: "אַל", at: "al" },
            { h: "תַּט", at: "tat" },
            { h: "בְּאַף", at: "b'af" },
            { h: "עַבְדֶּךָ", at: "avdecho" },
            { h: "עֶזְרָתִי", at: "ezrosi" },
            { h: "הָיִיתָ", at: "hoyiso" },
            { h: "אַל", at: "al" },
            { h: "תִּטְּשֵׁנִי", at: "tit'sheini" },
            { h: "וְאַל", at: "v'al" },
            { h: "תַּעַזְבֵנִי", at: "ta'azveini" },
            { h: "אֱלֹהֵי", at: "Elohei" },
            { h: "יִשְׁעִי", at: "yishi" },

            { h: "כִּי", at: "Ki", newParagraph: true },
            { h: "אָבִי", at: "ovi" },
            { h: "וְאִמִּי", at: "v'imi" },
            { h: "עֲזָבוּנִי", at: "azovuni" },
            { h: "וַייָ", at: "va'Adonai" },
            { h: "יַאַסְפֵנִי", at: "ya'asfeini" },

            { h: "הוֹרֵנִי", at: "Horeini", newParagraph: true },
            { h: "יְיָ", at: "Adonai" },
            { h: "דַּרְכֶּךָ", at: "dar'kecho" },
            { h: "וּנְחֵנִי", at: "u'n'cheini" },
            { h: "בְּאֹרַח", at: "b'orach" },
            { h: "מִישׁוֹר", at: "mishor" },
            { h: "לְמַעַן", at: "l'maan" },
            { h: "שׁוֹרְרָי", at: "shor'rai" },

            { h: "אַל", at: "Al", newParagraph: true },
            { h: "תִּתְּנֵנִי", at: "tit'neini" },
            { h: "בְּנֶפֶשׁ", at: "b'nefesh" },
            { h: "צָרָי", at: "tzorai" },
            { h: "כִּי", at: "ki" },
            { h: "קָמוּ", at: "komu" },
            { h: "בִי", at: "vi" },
            { h: "עֵדֵי", at: "eidei" },
            { h: "שֶׁקֶר", at: "sheker" },
            { h: "וִיפֵחַ", at: "vifei'ach" },
            { h: "חָמָס", at: "chomos" },

            { h: "לוּלֵא", at: "Lulei", newParagraph: true },
            { h: "הֶאֱמַנְתִּי", at: "he'emanti" },
            { h: "לִרְאוֹת", at: "liros" },
            { h: "בְּטוּב", at: "b'tuv" },
            { h: "יְיָ", at: "Adonai" },
            { h: "בְּאֶרֶץ", at: "b'eretz" },
            { h: "חַיִּים", at: "chayim" },

            { h: "קַוֵּה", at: "Kavei", newParagraph: true },
            { h: "אֶל", at: "el" },
            { h: "יְיָ", at: "Adonai" },
            { h: "חֲזַק", at: "chazak" },
            { h: "וְיַאֲמֵץ", at: "v'ya'ameitz" },
            { h: "לִבֶּךָ", at: "libecho" },
            { h: "וְקַוֵּה", at: "v'kavei" },
            { h: "אֶל", at: "el" },
            { h: "יְיָ", at: "Adonai" }
        ]
    }
};
