// Shema - central prayers including blessings before and after the Shema
const shemaPrayers = {
    yotzer_or: {
        title: "Yotzer Or (Morning Blessing Before Shema)",
        words: [
            { h: "בָּרוּךְ", at: "Boruch", newParagraph: true },
            { h: "אַתָּה", at: "atoh" },
            { h: "יְיָ", at: "Adonai" },
            { h: "אֱלֹהֵינוּ", at: "Eloheinu" },
            { h: "מֶלֶךְ", at: "melech" },
            { h: "הָעוֹלָם", at: "ho'olom" },
            { h: "יוֹצֵר", at: "yotzer" },
            { h: "אוֹר", at: "or" },
            { h: "וּבוֹרֵא", at: "u'vorei" },
            { h: "חֹשֶׁךְ", at: "choshech" },
            { h: "עֹשֶׂה", at: "oseh" },
            { h: "שָׁלוֹם", at: "sholom" },
            { h: "וּבוֹרֵא", at: "u'vorei" },
            { h: "אֶת", at: "es" },
            { h: "הַכֹּל", at: "hakol" }
        ]
    },

    ahavah_rabbah: {
        title: "Ahavah Rabbah (Love Blessing Before Shema)",
        words: [
            { h: "אַהֲבָה", at: "Ahavah", newParagraph: true },
            { h: "רַבָּה", at: "raboh" },
            { h: "אֲהַבְתָּנוּ", at: "ahavtonu" },
            { h: "יְיָ", at: "Adonai" },
            { h: "אֱלֹהֵינוּ", at: "Eloheinu" },
            { h: "חֶמְלָה", at: "chemlah" },
            { h: "גְדוֹלָה", at: "g'doloh" },
            { h: "וִיתֵרָה", at: "viseiroh" },
            { h: "חָמַלְתָּ", at: "chomaltoh" },
            { h: "עָלֵינוּ", at: "oleinu" },

            { h: "אָבִינוּ", at: "Ovinu", newParagraph: true },
            { h: "מַלְכֵּנוּ", at: "malkeinu" },
            { h: "בַּעֲבוּר", at: "ba'avur" },
            { h: "אֲבוֹתֵינוּ", at: "avoseinu" },
            { h: "שֶׁבָּטְחוּ", at: "shebotchu" },
            { h: "בְךָ", at: "v'cho" },
            { h: "וַתְּלַמְּדֵם", at: "vat'lam'deim" },
            { h: "חֻקֵּי", at: "chukei" },
            { h: "חַיִּים", at: "chayim" },
            { h: "כֵּן", at: "kein" },
            { h: "תְּחָנֵּנוּ", at: "t'choneinu" },
            { h: "וּתְלַמְּדֵנוּ", at: "u's'lam'deinu" },

            { h: "אָבִינוּ", at: "Ovinu", newParagraph: true },
            { h: "אָב", at: "ov" },
            { h: "הָרַחֲמָן", at: "horachamon" },
            { h: "הַמְרַחֵם", at: "ham'racheim" },
            { h: "רַחֵם", at: "racheim" },
            { h: "עָלֵינוּ", at: "oleinu" },
            { h: "וְתֵן", at: "v'sein" },
            { h: "בְּלִבֵּנוּ", at: "b'libeinu" },
            { h: "לְהָבִין", at: "l'hovin" },
            { h: "וּלְהַשְׂכִּיל", at: "u'l'haskil" },
            { h: "לִשְׁמֹעַ", at: "lishmo'a" },
            { h: "לִלְמֹד", at: "lilmod" },
            { h: "וּלְלַמֵּד", at: "u'l'lameid" },
            { h: "לִשְׁמֹר", at: "lishmor" },
            { h: "וְלַעֲשׂוֹת", at: "v'la'asos" },
            { h: "וּלְקַיֵּם", at: "u'l'kayeim" },
            { h: "אֶת", at: "es" },
            { h: "כָּל", at: "kol" },
            { h: "דִּבְרֵי", at: "divrei" },
            { h: "תַלְמוּד", at: "talmud" },
            { h: "תּוֹרָתֶךָ", at: "torosecho" },
            { h: "בְּאַהֲבָה", at: "b'ahavoh" },

            { h: "וְהָאֵר", at: "V'ho'eir", newParagraph: true },
            { h: "עֵינֵינוּ", at: "eineinu" },
            { h: "בְּתוֹרָתֶךָ", at: "b'sorosecho" },
            { h: "וְדַבֵּק", at: "v'dabeik" },
            { h: "לִבֵּנוּ", at: "libeinu" },
            { h: "בְּמִצְוֹתֶיךָ", at: "b'mitzvosecho" },
            { h: "וְיַחֵד", at: "v'yacheid" },
            { h: "לְבָבֵנוּ", at: "l'voveinu" },
            { h: "לְאַהֲבָה", at: "l'ahavoh" },
            { h: "וּלְיִרְאָה", at: "u'l'yir'oh" },
            { h: "אֶת", at: "es" },
            { h: "שְׁמֶךָ", at: "sh'mecho" },
            { h: "וְלֹא", at: "v'lo" },
            { h: "נֵבוֹשׁ", at: "neivosh" },
            { h: "לְעוֹלָם", at: "l'olom" },
            { h: "וָעֶד", at: "vo'ed" },

            { h: "כִּי", at: "Ki", newParagraph: true },
            { h: "בְשֵׁם", at: "v'sheim" },
            { h: "קָדְשְׁךָ", at: "kodsh'cho" },
            { h: "הַגָּדוֹל", at: "hagodol" },
            { h: "וְהַנּוֹרָא", at: "v'hanora" },
            { h: "בָּטָחְנוּ", at: "botachnu" },
            { h: "נָגִילָה", at: "nogiloh" },
            { h: "וְנִשְׂמְחָה", at: "v'nism'choh" },
            { h: "בִּישׁוּעָתֶךָ", at: "bishu'osecho" },

            { h: "וַהֲבִיאֵנוּ", at: "Vaha'vieinu", newParagraph: true },
            { h: "לְשָׁלוֹם", at: "l'sholom" },
            { h: "מֵאַרְבַּע", at: "mei'arba" },
            { h: "כַּנְפוֹת", at: "kanfos" },
            { h: "הָאָרֶץ", at: "ho'oretz" },
            { h: "וְתוֹלִיכֵנוּ", at: "v'solicheinu" },
            { h: "קוֹמְמִיּוּת", at: "kom'miyus" },
            { h: "לְאַרְצֵנוּ", at: "l'artzeinu" },

            { h: "כִּי", at: "Ki", newParagraph: true },
            { h: "אֵל", at: "Eil" },
            { h: "פּוֹעֵל", at: "po'eil" },
            { h: "יְשׁוּעוֹת", at: "y'shu'os" },
            { h: "אָתָּה", at: "atoh" },
            { h: "וּבָנוּ", at: "u'vonu" },
            { h: "בָחַרְתָּ", at: "vocharTo" },
            { h: "מִכָּל", at: "mikol" },
            { h: "עַם", at: "am" },
            { h: "וְלָשׁוֹן", at: "v'loshon" },
            { h: "וְקֵרַבְתָּנוּ", at: "v'keiravtonu" },
            { h: "לְשִׁמְךָ", at: "l'shimcho" },
            { h: "הַגָּדוֹל", at: "hagodol" },
            { h: "סֶלָה", at: "selah" },
            { h: "בֶּאֱמֶת", at: "be'emes" },
            { h: "לְהוֹדוֹת", at: "l'hodos" },
            { h: "לְךָ", at: "l'cho" },
            { h: "וּלְיַחֶדְךָ", at: "u'l'yached'cho" },
            { h: "בְּאַהֲבָה", at: "b'ahavoh" },

            { h: "בָּרוּךְ", at: "Boruch", newParagraph: true },
            { h: "אַתָּה", at: "atoh" },
            { h: "יְיָ", at: "Adonai" },
            { h: "הַבּוֹחֵר", at: "habocher" },
            { h: "בְּעַמּוֹ", at: "b'amo" },
            { h: "יִשְׂרָאֵל", at: "Yisroel" },
            { h: "בְּאַהֲבָה", at: "b'ahavoh" }
        ]
    },

    shema_paragraph_1: {
        title: "Shema - First Paragraph",
        words: [
            // First sentence
            { h: "שְׁמַע", at: "Sh'ma", newParagraph: true,
		        instructions: "During this verse, cover eyes with right hand." },
            { h: "יִשְׂרָאֵל", at: "Yisroel" },
            { h: "יְיָ", at: "Adonai" },
            { h: "אֱלֹהֵינוּ", at: "Eloheinu" },
            { h: "יְיָ", at: "Adonai" },
            { h: "אֶחָד", at: "echod" },
            
            // Second sentence - said quietly
            { h: "בָּרוּךְ", at: "Boruch", newParagraph: true,
		        instructions: "Say this sentence under your breath." },
            { h: "שֵׁם", at: "sheim" },
            { h: "כְּבוֹד", at: "k'vod" },
            { h: "מַלְכוּתוֹ", at: "malchuso" },
            { h: "לְעוֹלָם", at: "l'olom" },
            { h: "וָעֶד", at: "vo'ed" },
            
            // Third sentence
            { h: "וְאָהַבְתָּ", at: "V'ohavto", newParagraph: true },
            { h: "אֵת", at: "es" },
            { h: "יְיָ", at: "Adonai" },
            { h: "אֱלֹהֶיךָ", at: "Elohecho" },
            { h: "בְּכָל", at: "b'chol" },
            { h: "לְבָבְךָ", at: "l'vovcho" },
            { h: "וּבְכָל", at: "u'v'chol" },
            { h: "נַפְשְׁךָ", at: "nafsh'cho" },
            { h: "וּבְכָל", at: "u'v'chol" },
            { h: "מְאֹדֶךָ", at: "m'odecho" },
            
            // Fourth sentence
            { h: "וְהָיוּ", at: "V'hoyu", newParagraph: true },
            { h: "הַדְּבָרִים", at: "had'vorim" },
            { h: "הָאֵלֶּה", at: "ho'eileh" },
            { h: "אֲשֶׁר", at: "asher" },
            { h: "אָנֹכִי", at: "onochi" },
            { h: "מְצַוְּךָ", at: "m'tzav'cho" },
            { h: "הַיּוֹם", at: "hayom" },
            { h: "עַל", at: "al" },
            { h: "לְבָבֶךָ", at: "l'vovecho" },
            
            // Fifth sentence
            { h: "וְשִׁנַּנְתָּם", at: "V'shinantom", newParagraph: true },
            { h: "לְבָנֶיךָ", at: "l'vonecho" },
            { h: "וְדִבַּרְתָּ", at: "v'dibarto" },
            { h: "בָּם", at: "bom" },
            { h: "בְּשִׁבְתְּךָ", at: "b'shiv't'cho" },
            { h: "בְּבֵיתֶךָ", at: "b'veisecho" },
            { h: "וּבְלֶכְתְּךָ", at: "u'v'lecht'cho" },
            { h: "בַדֶּרֶךְ", at: "vaderech" },
            { h: "וּבְשָׁכְבְּךָ", at: "u'v'shochb'cho" },
            { h: "וּבְקוּמֶךָ", at: "u'v'kumecho" },
            
            // Sixth sentence
            { h: "וּקְשַׁרְתָּם", at: "U'k'shartom", newParagraph: true },
            { h: "לְאוֹת", at: "l'os" },
            { h: "עַל", at: "al" },
            { h: "יָדֶךָ", at: "yodecho" },
            { h: "וְהָיוּ", at: "v'hoyu" },
            { h: "לְטוֹטָפֹת", at: "l'totofos" },
            { h: "בֵּין", at: "bein" },
            { h: "עֵינֶיךָ", at: "einecho" },
            
            // Seventh sentence
            { h: "וּכְתַבְתָּם", at: "U'chsavtom", newParagraph: true },
            { h: "עַל", at: "al" },
            { h: "מְזוּזוֹת", at: "m'zuzos" },
            { h: "בֵּיתֶךָ", at: "beisecho" },
            { h: "וּבִשְׁעָרֶיךָ", at: "u'vish'orecho" }
        ]
    },

    shema_paragraph_2: {
        title: "Shema - Second Paragraph",
        words: [
            // Second paragraph (V'haya im shamoa)
            { h: "וְהָיָה", at: "V'hoya", newParagraph: true },
            { h: "אִם", at: "im" },
            { h: "שָׁמֹעַ", at: "shomoa" },
            { h: "תִּשְׁמְעוּ", at: "tishm'u" },
            { h: "אֶל", at: "el" },
            { h: "מִצְוֹתַי", at: "mitzvosai" },
            { h: "אֲשֶׁר", at: "asher" },
            { h: "אָנֹכִי", at: "onochi" },
            { h: "מְצַוֶּה", at: "m'tzaveh" },
            { h: "אֶתְכֶם", at: "eschem" },
            { h: "הַיּוֹם", at: "hayom" },
            { h: "לְאַהֲבָה", at: "l'ahavoh" },
            { h: "אֶת", at: "es" },
            { h: "יְיָ", at: "Adonai" },
            { h: "אֱלֹהֵיכֶם", at: "Eloheichem" },
            { h: "וּלְעָבְדוֹ", at: "u'l'ovdo" },
            { h: "בְּכָל", at: "b'chol" },
            { h: "לְבַבְכֶם", at: "l'vavchem" },
            { h: "וּבְכָל", at: "u'v'chol" },
            { h: "נַפְשְׁכֶם", at: "nafsh'chem" },

            { h: "וְנָתַתִּי", at: "V'nosati", newParagraph: true },
            { h: "מְטַר", at: "m'tar" },
            { h: "אַרְצְכֶם", at: "artzechem" },
            { h: "בְּעִתּוֹ", at: "b'ito" },
            { h: "יוֹרֶה", at: "yoreh" },
            { h: "וּמַלְקוֹשׁ", at: "u'malkosh" },
            { h: "וְאָסַפְתָּ", at: "v'osafto" },
            { h: "דְגָנֶךָ", at: "d'gonecho" },
            { h: "וְתִירֹשְׁךָ", at: "v'sirosh'cho" },
            { h: "וְיִצְהָרֶךָ", at: "v'yitzhorecho" },

            { h: "וְנָתַתִּי", at: "V'nosati", newParagraph: true },
            { h: "עֵשֶׂב", at: "eisev" },
            { h: "בְּשָׂדְךָ", at: "b'sod'cho" },
            { h: "לִבְהֶמְתֶּךָ", at: "livhemtecho" },
            { h: "וְאָכַלְתָּ", at: "v'ochalto" },
            { h: "וְשָׂבָעְתָּ", at: "v'sovoto" },

            { h: "הִשָּׁמְרוּ", at: "Hishomru", newParagraph: true },
            { h: "לָכֶם", at: "lochem" },
            { h: "פֶּן", at: "pen" },
            { h: "יִפְתֶּה", at: "yifteh" },
            { h: "לְבַבְכֶם", at: "l'vavchem" },
            { h: "וְסַרְתֶּם", at: "v'sartem" },
            { h: "וַעֲבַדְתֶּם", at: "va'avadtem" },
            { h: "אֱלֹהִים", at: "elohim" },
            { h: "אֲחֵרִים", at: "acheirim" },
            { h: "וְהִשְׁתַּחֲוִיתֶם", at: "v'hishtachavitem" },
            { h: "לָהֶם", at: "lohem" },

            { h: "וְחָרָה", at: "V'chorah", newParagraph: true },
            { h: "אַף", at: "af" },
            { h: "יְיָ", at: "Adonai" },
            { h: "בָּכֶם", at: "bochem" },
            { h: "וְעָצַר", at: "v'otzar" },
            { h: "אֶת", at: "es" },
            { h: "הַשָּׁמַיִם", at: "hashomayim" },
            { h: "וְלֹא", at: "v'lo" },
            { h: "יִהְיֶה", at: "yihyeh" },
            { h: "מָטָר", at: "motor" },
            { h: "וְהָאֲדָמָה", at: "v'ho'adomoh" },
            { h: "לֹא", at: "lo" },
            { h: "תִתֵּן", at: "sitein" },
            { h: "אֶת", at: "es" },
            { h: "יְבוּלָהּ", at: "y'vuloh" },
            { h: "וַאֲבַדְתֶּם", at: "va'avadtem" },
            { h: "מְהֵרָה", at: "m'heiroh" },
            { h: "מֵעַל", at: "mei'al" },
            { h: "הָאָרֶץ", at: "ho'oretz" },
            { h: "הַטֹּבָה", at: "hatovoh" },
            { h: "אֲשֶׁר", at: "asher" },
            { h: "יְיָ", at: "Adonai" },
            { h: "נֹתֵן", at: "nosein" },
            { h: "לָכֶם", at: "lochem" },

            { h: "וְשַׂמְתֶּם", at: "V'samtem", newParagraph: true },
            { h: "אֶת", at: "es" },
            { h: "דְּבָרַי", at: "d'vorai" },
            { h: "אֵלֶּה", at: "eileh" },
            { h: "עַל", at: "al" },
            { h: "לְבַבְכֶם", at: "l'vavchem" },
            { h: "וְעַל", at: "v'al" },
            { h: "נַפְשְׁכֶם", at: "nafsh'chem" },
            { h: "וּקְשַׁרְתֶּם", at: "u'k'shartem" },
            { h: "אֹתָם", at: "osom" },
            { h: "לְאוֹת", at: "l'os" },
            { h: "עַל", at: "al" },
            { h: "יֶדְכֶם", at: "yedchem" },
            { h: "וְהָיוּ", at: "v'hoyu" },
            { h: "לְטוֹטָפֹת", at: "l'totofos" },
            { h: "בֵּין", at: "bein" },
            { h: "עֵינֵיכֶם", at: "eineichem" },

            { h: "וְלִמַּדְתֶּם", at: "V'limadtem", newParagraph: true },
            { h: "אֹתָם", at: "osom" },
            { h: "אֶת", at: "es" },
            { h: "בְּנֵיכֶם", at: "b'neichem" },
            { h: "לְדַבֵּר", at: "l'dabeir" },
            { h: "בָּם", at: "bom" },
            { h: "בְּשִׁבְתְּךָ", at: "b'shiv't'cho" },
            { h: "בְּבֵיתֶךָ", at: "b'veisecho" },
            { h: "וּבְלֶכְתְּךָ", at: "u'v'lecht'cho" },
            { h: "בַדֶּרֶךְ", at: "vaderech" },
            { h: "וּבְשָׁכְבְּךָ", at: "u'v'shochb'cho" },
            { h: "וּבְקוּמֶךָ", at: "u'v'kumecho" },

            { h: "וּכְתַבְתָּם", at: "U'chsavtom", newParagraph: true },
            { h: "עַל", at: "al" },
            { h: "מְזוּזוֹת", at: "m'zuzos" },
            { h: "בֵּיתֶךָ", at: "beisecho" },
            { h: "וּבִשְׁעָרֶיךָ", at: "u'vish'orecho" },

            { h: "לְמַעַן", at: "L'maan", newParagraph: true },
            { h: "יִרְבּוּ", at: "yirbu" },
            { h: "יְמֵיכֶם", at: "y'meichem" },
            { h: "וִימֵי", at: "vimei" },
            { h: "בְנֵיכֶם", at: "v'neichem" },
            { h: "עַל", at: "al" },
            { h: "הָאֲדָמָה", at: "ho'adomoh" },
            { h: "אֲשֶׁר", at: "asher" },
            { h: "נִשְׁבַּע", at: "nishba" },
            { h: "יְיָ", at: "Adonai" },
            { h: "לַאֲבֹתֵיכֶם", at: "la'avoseichem" },
            { h: "לָתֵת", at: "loseis" },
            { h: "לָהֶם", at: "lohem" },
            { h: "כִּימֵי", at: "kimei" },
            { h: "הַשָּׁמַיִם", at: "hashomayim" },
            { h: "עַל", at: "al" },
            { h: "הָאָרֶץ", at: "ho'oretz" }
        ]
    },

    shema_paragraph_3: {
        title: "Shema - Third Paragraph",
        words: [
            // Third paragraph (Vayomer)
            { h: "וַיֹּאמֶר", at: "Vayomer", newParagraph: true },
            { h: "יְיָ", at: "Adonai" },
            { h: "אֶל", at: "el" },
            { h: "מֹשֶׁה", at: "Mosheh" },
            { h: "לֵּאמֹר", at: "leimor" },

            { h: "דַּבֵּר", at: "Dabeir", newParagraph: true },
            { h: "אֶל", at: "el" },
            { h: "בְּנֵי", at: "b'nei" },
            { h: "יִשְׂרָאֵל", at: "Yisroel" },
            { h: "וְאָמַרְתָּ", at: "v'omarto" },
            { h: "אֲלֵהֶם", at: "aleihem" },
            { h: "וְעָשׂוּ", at: "v'osu" },
            { h: "לָהֶם", at: "lohem" },
            { h: "צִיצִת", at: "tzitzis" },
            { h: "עַל", at: "al" },
            { h: "כַּנְפֵי", at: "kanfei" },
            { h: "בִגְדֵיהֶם", at: "vigdeihem" },
            { h: "לְדֹרֹתָם", at: "l'dorosom" },
            { h: "וְנָתְנוּ", at: "v'nosnu" },
            { h: "עַל", at: "al" },
            { h: "צִיצִת", at: "tzitzis" },
            { h: "הַכָּנָף", at: "hakonof" },
            { h: "פְּתִיל", at: "p'sil" },
            { h: "תְּכֵלֶת", at: "t'cheiles" },

            { h: "וְהָיָה", at: "V'hoya", newParagraph: true },
            { h: "לָכֶם", at: "lochem" },
            { h: "לְצִיצִת", at: "l'tzitzis" },
            { h: "וּרְאִיתֶם", at: "u'r'isem" },
            { h: "אֹתוֹ", at: "oso" },
            { h: "וּזְכַרְתֶּם", at: "u'z'chartem" },
            { h: "אֶת", at: "es" },
            { h: "כָּל", at: "kol" },
            { h: "מִצְוֹת", at: "mitzvos" },
            { h: "יְיָ", at: "Adonai" },
            { h: "וַעֲשִׂיתֶם", at: "va'asisem" },
            { h: "אֹתָם", at: "osom" },
            { h: "וְלֹא", at: "v'lo" },
            { h: "תָתוּרוּ", at: "sosuru" },
            { h: "אַחֲרֵי", at: "acharei" },
            { h: "לְבַבְכֶם", at: "l'vavchem" },
            { h: "וְאַחֲרֵי", at: "v'acharei" },
            { h: "עֵינֵיכֶם", at: "eineichem" },
            { h: "אֲשֶׁר", at: "asher" },
            { h: "אַתֶּם", at: "atem" },
            { h: "זֹנִים", at: "zonim" },
            { h: "אַחֲרֵיהֶם", at: "achareihem" },

            { h: "לְמַעַן", at: "L'maan", newParagraph: true },
            { h: "תִּזְכְּרוּ", at: "tizkru" },
            { h: "וַעֲשִׂיתֶם", at: "va'asisem" },
            { h: "אֶת", at: "es" },
            { h: "כָּל", at: "kol" },
            { h: "מִצְוֹתָי", at: "mitzvosai" },
            { h: "וִהְיִיתֶם", at: "vihyisem" },
            { h: "קְדֹשִׁים", at: "k'doshim" },
            { h: "לֵאלֹהֵיכֶם", at: "lEiloheichem" },

            { h: "אֲנִי", at: "Ani", newParagraph: true },
            { h: "יְיָ", at: "Adonai" },
            { h: "אֱלֹהֵיכֶם", at: "Eloheichem" },
            { h: "אֲשֶׁר", at: "asher" },
            { h: "הוֹצֵאתִי", at: "hotzaisi" },
            { h: "אֶתְכֶם", at: "eschem" },
            { h: "מֵאֶרֶץ", at: "mei'eretz" },
            { h: "מִצְרַיִם", at: "Mitzrayim" },
            { h: "לִהְיוֹת", at: "lihyos" },
            { h: "לָכֶם", at: "lochem" },
            { h: "לֵאלֹהִים", at: "lEilohim" },
            { h: "אֲנִי", at: "ani" },
            { h: "יְיָ", at: "Adonai" },
            { h: "אֱלֹהֵיכֶם", at: "Eloheichem" }
        ]
    },

    emet_vyatziv: {
        title: "Emet V'Yatziv (Truth Blessing After Shema)",
        words: [
            { h: "אֱמֶת", at: "Emes", newParagraph: true },
            { h: "וְיַצִּיב", at: "v'yatziv" },
            { h: "וְנָכוֹן", at: "v'nochon" },
            { h: "וְקַיָּם", at: "v'kayom" },
            { h: "וְיָשָׁר", at: "v'yoshor" },
            { h: "וְנֶאֱמָן", at: "v'ne'emon" },
            { h: "וְאָהוּב", at: "v'ohuv" },
            { h: "וְחָבִיב", at: "v'choviv" },
            { h: "וְנֶחְמָד", at: "v'nechmad" },
            { h: "וְנָעִים", at: "v'no'im" },
            { h: "וְנוֹרָא", at: "v'nora" },
            { h: "וְאַדִּיר", at: "v'adir" },
            { h: "וּמְתֻקָּן", at: "u'm'sukan" },
            { h: "וּמְקֻבָּל", at: "u'm'kubal" },
            { h: "וְטוֹב", at: "v'tov" },
            { h: "וְיָפֶה", at: "v'yofeh" },
            { h: "הַדָּבָר", at: "hadovor" },
            { h: "הַזֶּה", at: "hazeh" },
            { h: "עָלֵינוּ", at: "oleinu" },
            { h: "לְעוֹלָם", at: "l'olom" },
            { h: "וָעֶד", at: "vo'ed" },

            { h: "אֱמֶת", at: "Emes", newParagraph: true },
            { h: "אֱלֹהֵי", at: "Elohei" },
            { h: "עוֹלָם", at: "olom" },
            { h: "מַלְכֵּנוּ", at: "malkeinu" },
            { h: "צוּר", at: "tzur" },
            { h: "יַעֲקֹב", at: "Yaakov" },
            { h: "מָגֵן", at: "mogen" },
            { h: "יִשְׁעֵנוּ", at: "yish'einu" },

            { h: "מִי", at: "Mi", newParagraph: true },
            { h: "כָמוֹכָה", at: "chomocho" },
            { h: "בָּאֵלִם", at: "bo'eilim" },
            { h: "יְיָ", at: "Adonai" },
            { h: "מִי", at: "mi" },
            { h: "כָּמוֹכָה", at: "komocho" },
            { h: "נֶאְדָּר", at: "ne'dor" },
            { h: "בַּקֹּדֶשׁ", at: "bakodesh" },
            { h: "נוֹרָא", at: "nora" },
            { h: "תְהִלֹּת", at: "s'hilos" },
            { h: "עֹשֵׂה", at: "oseh" },
            { h: "פֶלֶא", at: "feleh" },

            { h: "יְיָ", at: "Adonai", newParagraph: true },
            { h: "יִמְלֹךְ", at: "yimloch" },
            { h: "לְעֹלָם", at: "l'olom" },
            { h: "וָעֶד", at: "vo'ed" },

            { h: "בָּרוּךְ", at: "Boruch", newParagraph: true },
            { h: "אַתָּה", at: "atoh" },
            { h: "יְיָ", at: "Adonai" },
            { h: "גָּאַל", at: "go'al" },
            { h: "יִשְׂרָאֵל", at: "Yisroel" }
        ]
    }
};